### PR TITLE
Backport/db per tenancy related

### PR DESCRIPTION
**Pull request by dougszumski**

### CODE REVIEW

**Comment by brtkwr** [comment]
Wait, all the db_per_tenant stuff was all released as part of the train release wasnt it?  Shouldnt we start from stable/train as a baseline and only backport extra changes?

**Comment by dougszumski** [comment]
It's all in Monasca API, but these patches didn't appear to make it into Monasca Persister. The branch name might be misleading as these aren't the main feature. I proposed https://review.opendev.org/#/c/692359 to be backported.

**Review by brtkwr — COMMENTED** [review]
LGTM

**Review by brtkwr — APPROVED** [review]
LGTM

**Pull request merged**
